version: '3.1'
services:
  app:
    container_name: springnative
    image: springnative
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgresql:14.7
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payments
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./admin/config:/docker-entrypoint-initdb.d